### ISSUE TITLE
Specify aria attributes

### ISSUE THREAD

**Issue by adamhammes-wf** [adamhammes/hammes.io#7]
For people using screen readers.

**Comment by adamhammes** [comment]
I don't think it's worth specifying the attributes on a page by page basis (at least for recipes and blogs). Rather, I should focus on having the templates have the aria attributes set.

**Comment by adamhammes** [comment]
After reading this link:

http://w3c.github.io/aria-in-html/

it doesn't look like I'm doing too bad, especially after bfd3e32.
